version: '3'

services:
  nginx:
    build:
      dockerfile: docker/nginx/prod/Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
